version: '3.4'

services:
  pdftools.api:
    image: ${DOCKER_REGISTRY-}pdftoolsapi
    build:
      context: .
      dockerfile: PdfTools.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
